name: Test Self PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Self PR Review
        uses: ./ # Use the local action
        with:
          review_bot_github_token: ${{ secrets.REVIEW_BOT_GITHUB_TOKEN }}
          llm_api_key: ${{ secrets.LLM_API_KEY }} # Ensure this secret is created in repo settings
          # Optional: Override other inputs if needed, otherwise defaults from action.yml are used
          # llm_model: 'anthropic/claude-3-haiku-20240307'
          # openhands_image: 'docker.all-hands.dev/all-hands-ai/openhands:0.32'
          # runtime_image: 'docker.all-hands.dev/all-hands-ai/runtime:0.32-nikolaik'
          # log_all_events: 'true'
          # review_prompt: |
          #   ... custom prompt ...
          # cli_args: '--some-arg' 